name: Script
# on: workflow_dispatch
on: 
    push:
        branches:
            - main
    # schedule:
    # - cron: "*/15 * * * *"
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        
        - name: checkout repo content
          uses: actions/checkout@v2 # checkout the repository content to github runner.
        - name: PHP Runner
          uses: franzliedke/gh-action-php@0.3.0

        - name: execute php script # run the script.php
          run: |
              php script.php brian-weloba ${{ secrets.flx_token }}}
              
        - name: commit files
          run: |
                git config --local user.email "bweloba@gmail.com"
                git config --local user.name "brian-weloba"
                git add -A
                git commit -m "run script.php" -a
        
        - name: push changes
          uses: ad-m/github-push-action@v0.6.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main 
